### ISSUE TITLE
Komitelerle yönetim

### ISSUE THREAD

**Issue by KiPSOFT** [aciksozluk/aciksozluk#12]
Merhaba;

Benim düşüncem her işlem için bir issue yerine komitelere ayrılmamız işin işleyişi açısından önemli noktalarda;

- Analiz Komitesi (Sistemin ihtiyaçlarını çıkaracak)
- Backend Teknik Komite (Sonra Sunucu Tarafı Geliştirme Komitesi olacak)
- Frontend Teknik Komite (Sonra Client Tarafı Geliştirme Komitesi olacak)
- Veritabanı Teknik Komite
- Sosyal Komite (Alımları ve yönetimleri ayarlayacak)

Teknik komiteler işe başlayana kadar mimari açısından karar verecekler daha sonra sistemin geliştirmesinde yer alacaklar. Bir kişi birden fazla komitede yer alabilir.

Tüm komitelerin haftalık çıkarımlarıyla genel bir IRC, Gitter veya Google Hangouts toplantısı düzenleyelim düşüncesindeyim ?

**Comment by onur** [comment]
Aslında bu konunun başlığını "Organizasyon yapısı" yaparak organizasyon üyelerini takımlara bölebiliriz.

Fakat yapılacak analizler de bir çok öznel yargı içereceğinden, komiteleri kurmak ve onların analizini bekleyip ardından tekrar bu analizleri tartışarak en iyisini seçmeye çalışarak bir arpa boyu yol katedemeyeceğimizi düşünüyorum.

**Comment by KiPSOFT** [comment]
Komite bireylerinin seçimlerini uzmanlıklarına göre yapabiliriz. Böylece öznel yargılar yerine genel yargılar elde etmiş oluruz. Bu organizasyon yapısı şu an olmasa bile ilerleyen aşamada bence bu şekle kendiliğinden bürünecek.
