### ISSUE TITLE
Owner yetkisi düzenleme

### ISSUE THREAD

**Issue by KiPSOFT** [aciksozluk/aciksozluk#25]
Arkadaşlar benim owner yetkimi düşürün lütfen. Teşekkürler.

**Comment by hqv** [comment]
Eventually, her şeyden önce güvenlik için, insanların(belki benim de) yetkilerini düşürmemiz gerekecek. 28 owner'ı olan bir organizasyon mu olur? Ancak bunun darbemsi bir hareket yerine uzlaşma ile olmasını tercih ederim.
