### ISSUE TITLE
28 owner?

### ISSUE THREAD

**Issue by hqv** [aciksozluk/aciksozluk#26]
Şu anda organizasyonumuzun 28 adet sahibi var, bu master'a istediği gibi pushlayabilen yahut [repositoryayı silebilen](https://github.com/aciksozluk/aciksozluk-api/issues/6) 28 kişi demek. Kişinin kötü niyetli olmasına da gerek yok, zaten conflict'siz PR'larda koskocaman yeşil buton çıkıyor merge'le diye.

Her ne kadar bu contributor'lar arasında ayrım oluşturacak olsa da, bir noktada yetkiyi ~~BANA~~ ~~benim seçeceğim birkaç kişiye~~ şu an için belirsiz bir yöntemle seçilecek n miktarda kişiye aktarmamız gerekecek.

Bu issue işbu sorunun tartışılması için oluşturulmuştur, fight!

**Comment by KiPSOFT** [comment]
Bence owner tek olmalı maksimum 2.

**Comment by ramesaliyev** [comment]
Organizasyonu açtıktan sonra kimseye ait olmasın diye herkesi owner olarak davet ettim. Et etkin destek veren 3-5 kişi haricindekilerin owner'lığını alabiliriz.

**Comment by ozziest** [comment]
Şahsen repo içerisinde hareket ederken korkuyorum yanlış bir butona basacağım diye. :) Benden bu yetki alınabilir. :+1:

**Comment by ramesaliyev** [comment]
Şu an için sessiz duran birkaç arkadaşı son durumdan haberdar olmadan hatayla yanlış bir şey yapmasınlar diye ve kendi isteği ile @ozziest'i :) owner'dan member'a çevirdim. 8 owner var.

Ek olarak takımlar oluşturup repolar üzerinde yetkilendirme yapabiliriz.

**Comment by readtimeout** [comment]
Ben takimdan cikarilmisim ?

**Comment by onur** [comment]
Audit log'a göre:  readtimeout removed themselves from the Açık Sözlük organization.

Tekrar invite attım

**Comment by readtimeout** [comment]
eyw @onur
